import type { RentalSnapshot } from '@/lib/rental-operations/types';

export const demoRentalSnapshot: RentalSnapshot = {
  source: 'demo',
  syncedAt: new Date().toISOString(),
  assets: [
    {
      id: 'asset-pw-001',
      barcode: '1',
      ain: 'PW-001',
      product: 'Vive Health Power Wheelchair',
      category: 'Power wheelchair',
      status: 'available',
    },
    {
      id: 'asset-pw-004',
      barcode: 'PW-004',
      ain: 'PW-004',
      product: 'Pride Go Chair',
      category: 'Power wheelchair',
      status: 'rented',
      customer: 'Customer linked from QuickBooks',
      dueDate: '2026-09-16',
      invoiceNumber: 'Invoice pending sync',
    },
    {
      id: 'asset-wc-001',
      barcode: '4',
      ain: 'WC-001',
      product: 'Medline K3 Lightweight Wheelchair',
      category: 'Wheelchair',
      status: 'due-today',
      customer: 'Customer linked from QuickBooks',
      dueDate: '2026-09-11',
      invoiceNumber: 'Invoice pending sync',
    },
    {
      id: 'asset-scooter-001',
      barcode: 'SCOOT-001',
      ain: 'SCOOT-001',
      product: 'Mobility Scooter',
      category: 'Scooter',
      status: 'overdue',
      customer: 'Customer linked from QuickBooks',
      dueDate: '2026-09-09',
      invoiceNumber: 'Invoice pending sync',
    },
    {
      id: 'asset-bed-001',
      barcode: 'BED-001',
      ain: 'BED-001',
      product: 'Full Electric Hospital Bed',
      category: 'Hospital bed',
      status: 'cleaning',
    },
    {
      id: 'asset-wc-002',
      barcode: 'WC-002',
      ain: 'WC-002',
      product: 'Transport Chair',
      category: 'Wheelchair',
      status: 'repair',
    },
  ],
};
